FROM php:7.3-apache

RUN apt -y update && apt-get install -y apt-utils
RUN apt install -y iputils-ping && apt-get install -y vsftpd && apt-get install -y nfs-kernel-server && apt-get install -y isc-dhcp-server && apt-get install -y bind9 dnsutils && apt-get install -y install telnetd && apt-get install -y install openssh-server openssh-client


